
package cuentas_correo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Juan David
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    correos co = new correos();
    conectar c = new conectar();
    Connection leer = c.conectar();
    PreparedStatement ps;
    String usuario;
    
    public login() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/Email.png")).getImage());
        setLocationRelativeTo(this);
    }
    public void iniciar(){
        if(txtusuario.getText().isEmpty()||jPassword.getText().isEmpty()){
            labelMensaje.setText("!ALGUN CAMPO ESTA VACIO¡");
            if(txtusuario.getText().isEmpty()){
                txtusuario.requestFocus();
            }else if(jPassword.getText().isEmpty()){
                jPassword.requestFocus();
            }
        }else{
            try{
             String SQL = "";
                Statement m = leer.createStatement();
                SQL = "SELECT * FROM usuarios WHERE usuario='"+txtusuario.getText() +"'";
                ResultSet q = m.executeQuery(SQL);
                String user = "", password = "";
                boolean encuentra = false;
                
                while(q.next()){
                    user = q.getString("usuario");
                    password = q.getString("password");
                }
                if(txtusuario.getText().equals(user) && jPassword.getText().equals(password)){
                    this.dispose();
                    encuentra = true;
                }
                if(encuentra){
                    co.setVisible(true);
                }else{
                    labelMensaje.setText("!USUARIO NO ENCONTRADO¡");
                    labelMensaje1.setText(" INTENTA NUEVAMENTE");
                }
            } catch(SQLException e){
                
            }  
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabelusuario = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabelcontraseña = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabellogo = new javax.swing.JLabel();
        labelMensaje1 = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(463, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUENTAS DE CORREO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 280, -1));

        txtusuario.setToolTipText("USUARIO");
        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 240, 20));

        jLabelusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo-usuario.png"))); // NOI18N
        getContentPane().add(jLabelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 315, 54));

        jPassword.setToolTipText("CONTRASEÑA");
        jPassword.setBorder(null);
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 20));

        jLabelcontraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campo-contrasena.png"))); // NOI18N
        getContentPane().add(jLabelcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 315, 63));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 370, 150));

        jPanel2.setBackground(new java.awt.Color(58, 159, 171));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Email.png"))); // NOI18N
        jLabellogo.setText("logo");
        jPanel2.add(jLabellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 104, 100));

        labelMensaje1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        labelMensaje1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labelMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 240, 20));

        labelMensaje.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 260, 20));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIAR SESIÓN");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
        iniciar();
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelcontraseña;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelMensaje1;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
